/* Generated By:JJTree: Do not edit this line. ASTgraph_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgraph_id extends SimpleNode {
  public ASTgraph_id(int id) {
    super(id);
  }

  public ASTgraph_id(DotParser p, int id) {
    super(p, id);
  }
  public void setName(String n){
      name=n;
  }
  public String toString(){
      return "GraphName: "+name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DotParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2bddfad266a5550e83f269b2f2bd753 (do not edit this line) */
